DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ADD_SUBJECT_COMBO_5`(
	dse1 VARCHAR(25), gec3 VARCHAR(25), vac7 VARCHAR(25), STUDENT_ID INT
)
BEGIN
	START TRANSACTION;
			SET @LAST_UPDATED_ID := 0;
			UPDATE student_semester SET DSE = dse1, GEC = gec3, VAC1 = vac7, ID = (SELECT @LAST_UPDATED_ID := ID) WHERE STUDENT_PROFILE_ID = STUDENT_ID AND SEMESTER = 5;
                     
            INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) VALUES (YEAR(curdate()),@LAST_UPDATED_ID,"DSE1",1,dse1) 
			ON DUPLICATE KEY UPDATE SUB_CODE = VALUES(SUB_CODE);
			INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) VALUES (YEAR(curdate()),@LAST_UPDATED_ID,"GEC3",1,gec3) 
			ON DUPLICATE KEY UPDATE SUB_CODE = VALUES(SUB_CODE);
			INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) VALUES (YEAR(curdate()),@LAST_UPDATED_ID,"VAC7",1,vac7) 
			ON DUPLICATE KEY UPDATE SUB_CODE = VALUES(SUB_CODE);
            
	COMMIT;
END$$
DELIMITER ;
