DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ADD_SUBJECT_COMBO_4`(
	gec2 VARCHAR(25), vac6 VARCHAR(25), STUDENT_ID INT
)
BEGIN
	START TRANSACTION;
			SET @LAST_UPDATED_ID := 0;
			UPDATE student_semester SET GEC = gec2,VAC1 = vac6, ID = (SELECT @LAST_UPDATED_ID := ID) WHERE STUDENT_PROFILE_ID = STUDENT_ID AND SEMESTER = 4;
                     
            INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) VALUES (YEAR(curdate()),@LAST_UPDATED_ID,"GEC2",1,gec2) 
			ON DUPLICATE KEY UPDATE SUB_CODE = VALUES(SUB_CODE);
			INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) VALUES (YEAR(curdate()),@LAST_UPDATED_ID,"VAC6",1,vac6) 
			ON DUPLICATE KEY UPDATE SUB_CODE = VALUES(SUB_CODE);
            
	COMMIT;
END$$
DELIMITER ;
