DROP PROCEDURE IF EXISTS ADD_SUBJECT_COMBO_1;
DELIMITER $$
CREATE PROCEDURE ADD_SUBJECT_COMBO_1(
	aecc VARCHAR(25), sec VARCHAR(25), vac1 VARCHAR(25), vac2 VARCHAR(25), STUDENT_ID INT
)
BEGIN
	START TRANSACTION;
			SET @LAST_UPDATED_ID := 0;
			UPDATE student_semester SET AECC = aecc,SEC = sec,VAC1 = vac1, VAC2 = vac2, ID = (SELECT @LAST_UPDATED_ID := ID) WHERE STUDENT_PROFILE_ID = STUDENT_ID AND SEMESTER = 1;
            -- SET @_LID = LAST_INSERT_ID();
-- 			INSERT INTO academic_record (STUDENT_SEMESTER_ID, ACADEMIC_YEAR, SUB_CODE,COURSE) VALUES (@LAST_UPDATED_ID, YEAR(curdate()), aecc, "AECC");
--             INSERT INTO academic_record (STUDENT_SEMESTER_ID, ACADEMIC_YEAR, SUB_CODE,COURSE) VALUES (@LAST_UPDATED_ID, YEAR(curdate()), sec, "SEC");
--             INSERT INTO academic_recNEW_STUDENTord (STUDENT_SEMESTER_ID, ACADEMIC_YEAR, SUB_CODE,COURSE) VALUES (@LAST_UPDATED_ID, YEAR(curdate()), vac1, "VAC1");
--             INSERT INTO academic_record (STUDENT_SEMESTER_ID, ACADEMIC_YEAR, SUB_CODE,COURSE) VALUES (@LAST_UPDATED_ID, YEAR(curdate()), vac2, "VAC2");
            
            INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) VALUES (YEAR(curdate()),@LAST_UPDATED_ID,"AECC",1,aecc) 
			ON DUPLICATE KEY UPDATE SUB_CODE = VALUES(SUB_CODE);
-- 			INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) VALUES (YEAR(curdate()),@LAST_UPDATED_ID,"AECC",1,aecc) 
-- 			ON DUPLICATE KEY UPDATE 
-- 			ACADEMIC_YEAR = VALUES(ACADEMIC_YEAR), STUDENT_SEMESTER_ID = VALUES(STUDENT_SEMESTER_ID), COURSE = VALUES(COURSE), SUB_CODE = VALUES(SUB_CODE);
			INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) VALUES (YEAR(curdate()),@LAST_UPDATED_ID,"SEC",1,sec) 
			ON DUPLICATE KEY UPDATE 
			ACADEMIC_YEAR = VALUES(ACADEMIC_YEAR), STUDENT_SEMESTER_ID = VALUES(STUDENT_SEMESTER_ID), COURSE = VALUES(COURSE), SUB_CODE = VALUES(SUB_CODE);
			INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) VALUES (YEAR(curdate()),@LAST_UPDATED_ID,"VAC1",1,vac1) 
			ON DUPLICATE KEY UPDATE 
			ACADEMIC_YEAR = VALUES(ACADEMIC_YEAR), STUDENT_SEMESTER_ID = VALUES(STUDENT_SEMESTER_ID), COURSE = VALUES(COURSE), SUB_CODE = VALUES(SUB_CODE);
			INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) VALUES (YEAR(curdate()),@LAST_UPDATED_ID,"VAC2",2,vac2) 
			ON DUPLICATE KEY UPDATE 
			ACADEMIC_YEAR = VALUES(ACADEMIC_YEAR), STUDENT_SEMESTER_ID = VALUES(STUDENT_SEMESTER_ID), COURSE = VALUES(COURSE), SUB_CODE = VALUES(SUB_CODE);
            
	COMMIT;
END $$

DELIMITER ;