DROP PROCEDURE IF EXISTS PROMOTE;
DELIMITER $$
CREATE PROCEDURE PROMOTE(
	SEM VARCHAR(25), YEAR VARCHAR(25), ID INT
)
BEGIN
	START TRANSACTION;
			UPDATE student_semester SET PROMOTED = "Y" WHERE student_semester.STUDENT_PROFILE_ID = ID;
            SET @_LAST_SEM = (SEM - 1);
			INSERT INTO student_semester (STUDENT_PROFILE_ID, SEM_YEAR, SEMESTER, DSC, DSE) 
				SELECT ID, YEAR, SEM, sem.DSC, sem.DSE FROM student_semester sem WHERE sem.STUDENT_PROFILE_ID = ID;
			INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) 
				SELECT sem.SEM_YEAR,LAST_INSERT_ID(),"CORE",p.PAPER,p.SUB_CODE FROM student_semester sem, papers p 
				WHERE p.COURSE = "CORE" AND p.SEMESTER = SEM AND sem.SEMESTER = @_LAST_SEM AND p.SUB = sem.DSC AND sem.STUDENT_PROFILE_ID = ID;
	COMMIT;
END $$

DELIMITER ;