DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `PROMOTE`(
	SEM VARCHAR(25), ACADEMIC_YEAR VARCHAR(25), ID INT, FEE_DUE VARCHAR(25)
)
BEGIN
	START TRANSACTION;
            SET @_LAST_SEM = (SEM - 1);
            UPDATE student_semester SET PROMOTED = "Y" WHERE student_semester.STUDENT_PROFILE_ID = ID AND student_semester.SEMESTER = @_LAST_SEM;
			INSERT INTO student_semester (STUDENT_PROFILE_ID, SEM_YEAR, SEMESTER, DSC, DSE) 
				SELECT ID, ACADEMIC_YEAR, SEM, sem.DSC, sem.DSE FROM student_semester sem WHERE sem.STUDENT_PROFILE_ID = ID AND sem.SEMESTER = @_LAST_SEM;
			SET @_SEM_ID = LAST_INSERT_ID();
			INSERT INTO academic_record (ACADEMIC_YEAR,STUDENT_SEMESTER_ID,COURSE,PAPER,SUB_CODE) 
				SELECT sem.SEM_YEAR,@_SEM_ID,"CORE",p.PAPER,p.SUB_CODE FROM student_semester sem, papers p 
				WHERE p.COURSE = "CORE" AND p.SEMESTER = SEM AND sem.SEMESTER = @_LAST_SEM AND p.SUB = sem.DSC AND sem.STUDENT_PROFILE_ID = ID;
			INSERT INTO student_fee (STUDENT_PROFILE_ID, STUDENT_SEMESTER_ID,ADM_FEE,EXM_FEE) VALUES (ID,@_SEM_ID,FEE_DUE,'UNPAID');
	COMMIT;
END$$
DELIMITER ;
